artifacts_root: artifacts 
#will create a folder called artifacts and all generation will get store in this folder



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/harsh-vardhan7695/Data/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]